### ISSUE TITLE
Utilities/Quaternion

### ISSUE THREAD

**Issue by AristurtleDev** [AristurtleDev/monogame-build-warning-tracker#44]
**File Path**: MonoGame.Framework/Utilities/System.Numerics.Vectors/Quaternion.cs

**CS1591**
- [x] Missing XML comment for publicly visible type or member 'Quaternion.X' [ Native ]
- [x] Missing XML comment for publicly visible type or member 'Quaternion.Y' [ Native ]
- [x] Missing XML comment for publicly visible type or member 'Quaternion.Z' [ Native ]
- [x] Missing XML comment for publicly visible type or member 'Quaternion.W' [ Native ]
- [x] Missing XML comment for publicly visible type or member 'Quaternion.Quaternion(float, float, float, float)' [ Native ]

**Comment by disappeaTed** [comment]
There is no such file or class (Utilities/System.Numerics.Vectors):

![Image](https://github.com/AristurtleDev/monogame-build-warning-tracker/assets/157877453/daf59abf-a3ea-4cc3-b003-8921aa076482)

**Comment by theLaffa** [comment]
Found the file if it helps


![Image](https://github.com/AristurtleDev/monogame-build-warning-tracker/assets/149337013/94ee2637-3180-4a15-9208-bf1f8401a6b2)
