### ISSUE TITLE
Graphics/RenderTargetCube

### ISSUE THREAD

**Issue by AristurtleDev** [AristurtleDev/monogame-build-warning-tracker#5]
**File Path**: MonoGame.Framework/Graphics/RenderTargetCube.cs

**CS0067**
- [x] The event 'RenderTargetCube.ContentLost' is never used [ WindowsUniversal, All Platforms ]

**Comment by disappeaTed** [comment]
![Image](https://github.com/AristurtleDev/monogame-build-warning-tracker/assets/157877453/b400d8e5-0ff3-42ea-b13d-1db12a4aa2c1)

Huh.
